# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaffa69e0be59d400028fd9f228d55592a6c19d453529517783b89743da6a0695cc1014c27adcb91a45c23601f45e1bc48f661d8170d4371495ff6c05567c6c9

test:
  secret_key_base: 9ac8170a2ec105ad20135e56d87ca1139c51d975bea962e1eb32f6d3b1c288b9fb0d7a11344b3ef5144d741110d33e33f2f58074ac4d25450bbc3f6a609548f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
